Highlight read
privat/rars pull request #34
Opened 2024-07-02 20:12 UTC by Shin-703

This is an answer to the issue #7 highlight read. This enhancement adds highlights when explicitly reading data (in data segment or register block) while executing step by step.

There is now two colors for these highlights (configurable by the user), blue for explicit reading and redish for explicit writing.

2024-07-03 14:27 UTC, privat commented
There are some errors on my machine, maybe some settings are not initialized properly

```
$ java -jar rars.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Color.equals(Object)" because "<local3>" is null
	at rars.venus.settings.SettingsHighlightingAction.initializeButtonColors(SettingsHighlightingAction.java:341)
	at rars.venus.settings.SettingsHighlightingAction.buildDialogPanel(SettingsHighlightingAction.java:175)
```

2024-07-03 16:37 UTC, privat commented
it works \o/ :tada:

2024-07-04 15:28 UTC, privat requested changes

2024-07-04 15:28 UTC, privat commented on src/rars/venus/registers/RegisterBlockWindow.java
> +        /*for (int i = 0; i < registers.length; i++) {
do not comment, delete

2024-07-04 15:28 UTC, privat commented on src/rars/venus/DataSegmentWindow.java
> +                    cell.setFont(settings.getFontByPosition(Settings.EXPLICIT_READ_HIGHLIGHT_FONT));
weird indentation

2024-07-04 19:27 UTC, Shin-703 commented on src/rars/venus/DataSegmentWindow.java
> +                    cell.setFont(settings.getFontByPosition(Settings.EXPLICIT_READ_HIGHLIGHT_FONT));
yes indeed

2024-07-04 19:50 UTC, merged